workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        APP_ID: "com.lepm.mobile"  # Замените на ваш Bundle ID
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd frontend
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios
          pod install
      - name: Build iOS
        script: |
          cd frontend
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app.dSYM.zip
    publishing:
      email:
        recipients:
          - your-email@example.com  # Замените на ваш email
        notify:
          success: true
          failure: false

